---
title: My R courses on Udemy
author: admin
date: '2021-08-03'
slug: []
categories: []
tags:
  - R course
  - R
  - udemy
  - regression
  - Machine Learning
subtitle: ''
summary: ''
authors: []
lastmod: '2021-08-03T17:04:02+02:00'
featured: yes
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Hi,
since I uploaded a brand new course on <https://www.udemy.com>, I would like to give you a brief overview on what you will learn in this course. For now it is available in german only, but the english version is under very active development. The course is called: *Regression Pipeline in R* and teaches you how to build a Pipeline using *tidymodels* with *workflowsets*. If you already know a little bit about *Machine Learning* and *R* this course is just right for you. If you just starting out using R and do not know much about Regression the pace is probably a bit high for you. Nevertheless you can enjoy the ride from a different perspective.

I also teach a Beginner´s course on udemy which is called *R Basics* unfortunately this course is available in german only. Translation is under active development also.

If you are interested in the courses, please use following links:

- <https://www.udemy.com/course/regressions-pipeline-r/?referralCode=CCF54A38E243A7CF646C>
You can use the coupon-code *F3D83F32BD427297682F* to get a discount if you like.

- <https://www.udemy.com/course/r-basics-u/?referralCode=294114E77907E6E07B63>

Thank you for reading.
Best,
Moritz

